---
title: "4-Hour Movie? Frankly, My Dear, I Don’t Give A Damn."
author: "Vivian Wang, Maggie Wang"
date: "December 3, 2017"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(RMySQL)
library(dplyr)
library(ggplot2)
library(ggthemes)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
# Pull information all at once from server via sql query
# Limited to films more than 60mins long, produced in the US, and not adult

ratelength_sql <- "
SELECT t.id, t.title, 
	t.production_year AS Year, 
  mii.info AS Rating,
  mi.info AS Length, 
  mii2.info AS Votes,
  mi4.info AS Genre
FROM title t
JOIN movie_info_idx mii ON mii.movie_id = t.id
JOIN movie_info mi ON mi.movie_id = t.id
JOIN movie_info_idx mii2 ON mii2.movie_id = t.id
JOIN movie_info mi2 ON mi2.movie_id = t.id
JOIN movie_info mi3 ON mi3.movie_id = t.id
JOIN movie_info mi4 ON mi4.movie_id = t.id
WHERE t.kind_id = 1
AND mii.info_type_id = 101
AND mi.info_type_id = 1
AND mi.info > 59
AND mii2.info_type_id = 100
AND mii2.info > 1000
AND mi2.info_type_id = 3
AND mi2.info NOT LIKE '%Adult%'
AND mi3.info_type_id = 8
AND mi3.info LIKE '%USA%'
AND mi4.info_type_id = 3
GROUP BY t.id;
"

ratelength <- db %>% 
  dbGetQuery(ratelength_sql) %>% 
  mutate(Length = as.integer(Length)) %>% 
  mutate(Rating = as.numeric (Rating)) %>% 
  mutate(Votes = as.integer(Votes)) %>% 
  mutate(Genre = as.factor(Genre))
```

```{r warning=FALSE}
# Find average film length over the years
avg_length <- ratelength %>% 
  group_by(Year) %>% 
  summarize(Length = mean(Length))

# Plot average length against year of film release
avg_length %>% ggplot(aes(x = Year, y = Length)) + 
  geom_point(shape = 18, color = "royalblue4") + 
  geom_line(color = "royalblue4") + 
  theme_wsj() + 
  theme(axis.title = element_text(size = 15)) + 
  scale_x_continuous(limits = c(1920, 2017),
                     breaks = c(1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010)) + 
  scale_y_continuous(name = "Movie Length", limits = c(60,150), 
                     breaks = c(60, 90, 120, 150),
                     labels = c("1h", "1.5h", "2h", "2.5h"))
```

```{r}
# Bin film length, find count and average rating
avg_rating_length <- ratelength %>% 
  mutate(Length = cut(ratelength$Length, 
                      breaks = c(-Inf, 90, 120, 150, 180, 210, Inf), 
                      labels = c("1h", "1.5h", "2h", "2.5h", "3h", "3.5h+"),
                      include.lowest = TRUE)) %>% 
  group_by(Length) %>% 
  summarize(num = n(), Rating = mean(Rating))
  
# Plot rating against length
# Size of diamond indicate number of films in the bin
avg_rating_length %>%
  ggplot(aes(x = Length, y = Rating)) + 
  geom_point(aes(size = num), shape = 18, 
             color = "royalblue4") + 
  geom_label(aes(label = num), nudge_y = .5) + 
  theme_wsj() + 
  scale_size(range = c(1,30)) + 
  theme(legend.position = "none") + 
  theme(axis.title = element_text(size = 15)) +
  scale_x_discrete(name = "Movie Length") +
  scale_y_continuous(name = "Average Rating", 
                     limits = c(5.5, 8.35))
```

```{r}
# Find information about films longer than 3h
genre_long <- ratelength %>% 
  filter(Length >= 180)

# Count number of long films according to genre
genre_long_num <- genre_long %>% 
  group_by(Genre) %>% 
  summarize(num = n())

# Plot in bar graph
genre_long_num %>% 
  ggplot(aes(x = reorder(Genre,-num), y = num)) + 
  geom_bar(stat = "identity", 
           fill = "royalblue4", width = .5) + 
  theme_wsj() + 
  scale_x_discrete(name = "Genre") + 
  scale_y_continuous(name = "Number of Long Films", 
                     limits = c(0, 25)) + 
  theme(axis.title = element_text(size = 15), 
        axis.text = element_text(size = 10))
```

